EXPERIMENT:
  NAME: "vgg13,vgg8"
  TAG: "vgg13,vgg8,titanxp"
  PROJECT: "cifar100_baselines_simkd"
DISTILLER:
  TYPE: "SIMKD"
  TEACHER: "vgg13"
  STUDENT: "vgg8"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"

LOG:
  WANDB: false
  # WANDB: true

device: 0

DATASET:
  AUTO_AUG: False
  CUT_OUT: False