EXPERIMENT:
  NAME: "reviewkd,res32x4,wrn_40_2,ReviewKD"
  TAG: "reviewkd,res32x4,wrn_40_2,ReviewKD"
  PROJECT: "cifar100_SFAKD"
DISTILLER:
  TYPE: "REVIEWKD"
  TEACHER: "resnet32x4"
  STUDENT: "wrn_40_2"
REVIEWKD:
  REVIEWKD_WEIGHT: 5.0
  SHAPES: [1,8,16,32]
  IN_CHANNELS: [32, 64, 128, 128]
  OUT_CHANNELS: [64, 128, 256, 256]
  # OUT_SHAPES: [1, 4, 8, 16, 32]
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"

LOG:
  WANDB: true
  # WANDB: false

