EXPERIMENT:
  NAME: "ResNet110x2_train_1"
  TAG: "vanilla,ResNet110x2,ResNet110x2"
  PROJECT: "cifar100_baselines_teacher_train"
DISTILLER:
  TYPE: "NONE"
  TEACHER: "ResNet110x2"
  STUDENT: "ResNet110x2"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"

LOG:
  # WANDB: false
  WANDB: true

device: 1

DATASET:
  AUTO_AUG: False
  CUT_OUT: False

