#512->512
EXPERIMENT:
  NAME: "vgg13,vgg8,oblation2"
  TAG: "vgg13,vgg8,oblation2"
  PROJECT: "cifar100_SFAKD"
DISTILLER:
  TYPE: "SFAKD_oblation2"
  TEACHER: "vgg13"
  STUDENT: "vgg8"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"

LOG:
  # WANDB: false
  WANDB: true

device: 0

DATASET:
  AUTO_AUG: False
  CUT_OUT: False

SFAKD:
  CUT_OFF: 0.5
